### ISSUE TITLE
Please replace 'import re as re' with just 'import re'

### ISSUE THREAD

**Issue by gvanrossum** [PrakharPythonProgrammer/Grail-0.6#5] opened 2021-05-18 15:56 UTC
I saw that you're changing all regex occurences to re, which is a good idea. But you've overcomplicated the import by writing
```
import re as re
```
This can just be
```
import re
```

**Comment by gvanrossum** [comment] 2021-05-18 15:59
(Also, though unrelated, please try to write better commit messages than "Added files via upload". I don't know if you're using a tool that uses this as the default commit message, and I understand that you're new at git and GitHub, but future generations will thank you for writing useful commit messages... :-)

If you Google around a bit you can find useful guides to writing better commit messages.

**Comment by PrakharPythonProgrammer** [comment] 2021-05-18 16:08
Ah regex was used at so many places so I directly used find and replace
function. So import regex as re got replaced with import re as re. I'll
change it as soon as possible.

Thanks for informing me

**Comment by PrakharPythonProgrammer** [comment] 2021-05-18 16:09
Ah regex was used at so many places so I directly used the find and replace
function. So import regex as re got replaced with import re as re. I'll
change it as soon as possible. Thanks for informing me.
I'll also try to write better commit messages from next time

**Comment by gvanrossum** [comment] 2021-05-18 17:25
I suspect that you are using some kind of global substitution mechanism in
your text editor. Maybe you should review the substitutions it made before
committing them to git. :-)

**Comment by PrakharPythonProgrammer** [comment] 2021-05-18 17:27
Yes you are absolutely right it's better to first review the code before
committing them to git

**Comment by PrakharPythonProgrammer** [comment] 2021-05-19 01:56
Now the problem is solved I am closing the issue.

**Closed by PrakharPythonProgrammer** 2021-05-19 01:56 UTC
